GenshinMVC/Models/CharacterVM.cs
using GenshinLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace GenshinMVC.Models
{
    public class CharacterVM
    {
        public int Id { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Name is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "A vision must be selected")]
        public Vision Vision { get; set; }
        [Required(ErrorMessage = "A region must be selected")]
        public Region Region { get; set; }
        [Required(ErrorMessage = "A weapon type must be selected")]
        public WeaponType Weapon { get; set; }
    }
}

GenshinMVC/Controllers/CharacterController.cs
using GenshinDAL;
using GenshinLibrary;
using GenshinMVC.Helpers.DALMapper;
using GenshinMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GenshinMVC.Controllers
{
    public class CharacterController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("GetCharacters");
        }

        public ActionResult GetCharacters()
        {
            var characters = CharacterDALMapper.List();
            return View(characters);
        }

    }
}

GenshinMVC/Controllers/CharacterDetailsController.cs
using GenshinDAL;
using GenshinLibrary;
using GenshinMVC.Helpers.DALMapper;
using GenshinMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GenshinMVC.Controllers
{
    [HandleError]
    public class CharacterDetailsController : Controller
    {
        const string ACTUAL_NAME_KEY = "actualName";

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [ActionName("Edit")]
        public ActionResult EditCharacter(int id)
        {
            return CharacterDetails(id, "EditCharacter");
        }

        [HttpGet]
        [ActionName("View")]
        public ActionResult ViewCharacter(int id)
        {
            return CharacterDetails(id, "ViewCharacter");
        }

        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditCharacter(CharacterVM model)
        {
            if (ModelState.IsValid)
            {
                if (IsNameAvailable(model.Name))
                {
                    #region Update character info
                    try
                    {
                        UpdateInfo(model);
                        return RedirectToAction("Index", "Character");

                    }
                    catch (Exception e)
                    {
                        ViewBag.ErrorMessage = e.Message;
                        return View("Error");
                    }
                    #endregion
                }
                else
                {
                    //Add custom error to the ModelState if the character already exists
                    ModelState.AddModelError("Name", "That name already exists");
                }
            }

            return View("EditCharacter", model);
        }

        [NonAction]
        public ActionResult CharacterDetails(int id, string viewName)
        {
            CharacterVM model = CharacterDALMapper.FindById(id);

            if (model == null)
            {
                return HttpNotFound();
            }

            //Get actual name and save it in a temporary state object
            TempData[ACTUAL_NAME_KEY] = model.Name;

            return View(viewName, model);
        }

        [NonAction]
        public void UpdateInfo(CharacterVM character)
        {
            var model = new CharacterVM()
            {
                Id = character.Id,
                Name = character.Name,
                Region = character.Region,
                Weapon = character.Weapon,
                Vision = character.Vision
            };

            CharacterDALMapper.Update(model);
        }

        private bool IsNameAvailable(string name)
        {
            if (CharacterDALMapper.FindByName(name) is null)
            {
                return true;
            }
            else
            {
                //Get actual name
                var actualName = TempData.ContainsKey(ACTUAL_NAME_KEY)
                                                        ? TempData[ACTUAL_NAME_KEY].ToString()
                                                        : String.Empty;

                //Store the actual name again for further invalid requests
                TempData[ACTUAL_NAME_KEY] = actualName;

                if (name.Equals(actualName, StringComparison.OrdinalIgnoreCase))
                {
                    return true;

                }

            }

            return false;

        }


    }
}

GenshinMVC/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GenshinMVC.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [ActionName("not-found")]
        public ActionResult NotFound()
        {
            Response.StatusCode = 404;
            return View("NotFound");
        }

        [HttpGet]
        [ActionName("internal-error")]
        public ActionResult InternalError()
        {
            Response.StatusCode = 500;
            return View("InternalError");
        }

        [HttpGet]
        [ActionName("bad-request")]
        public ActionResult BadRequest()
        {
            Response.StatusCode = 400;
            return View("BadRequest");
        }
    }
}

GenshinMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GenshinDAL;
using GenshinMVC.Helpers.DALMapper;

namespace GenshinMVC.Controllers
{
    public class HomeController : Controller
    {
        public HomeController()
        {
            //Instancio por única vez el DALMapper
            var mapper = new CharacterDALMapper(new CharactersDAL());

        }

        public ActionResult Index()
        {
            return RedirectToAction("Index", "Character");
        }

    }
}

GenshinMVC/Views/Character/GetCharacters.cshtml
@model IEnumerable<GenshinMVC.Models.CharacterVM>

@{
    ViewBag.Title = "Characters";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var characterIconURL = "https://rerollcdn.com/GENSHIN/Characters/";
    var elementIconURL = "https://rerollcdn.com/GENSHIN/Elements/";
}



<main class="content content-col">
    <header class="mt-2 mb-4">
        <h2 class="text-center">@ViewBag.Title</h2>
    </header>
    <div class="characters-list">
        @foreach (var character in Model)
        {
            <div class="character-container">
                <div class="character-portrait m-auto">
                    <img class="character-element"
                         src="@String.Concat(elementIconURL, "Element_", character.Vision, ".png")" alt="@character.Vision" />
                    <img class="character-icon"
                         src="@String.Concat(characterIconURL, character.Name,".png")" alt="@character.Name" />
                    <span class="character-name">@character.Name</span>
                    <div class="character-details">
                        <a href="@Url.Action("view", "CharacterDetails", new { id = character.Id})" target="_self">
                            <span class="material-icons details-icon"> visibility </span>
                        </a>
                        <a href="@Url.Action("edit", "CharacterDetails", new { id = character.Id})" target="_self">
                            <span class="material-icons details-icon"> edit </span>
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
</main>

@Scripts.Render("~/bundles/scripts")

GenshinMVC/Views/CharacterDetails/EditCharacter.cshtml
@model GenshinMVC.Models.CharacterVM
@using GenshinLibrary

@{
    ViewBag.Title = "Edit Character";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<main class="content">
    @*
            @{
                string textColor;

                switch (Model.Vision)
                {
                    case Vision.Anemo:
                        textColor = "text-anemo";
                        break;
                    case Vision.Pyro:
                        textColor = "text-pyro";
                        break;
                    case Vision.Hydro:
                        textColor = "text-hydro";
                        break;
                    case Vision.Dendro:
                        textColor = "text-dendro";
                        break;
                    case Vision.Cryo:
                        textColor = "text-cryo";
                        break;
                    case Vision.Geo:
                        textColor = "text-geo";
                        break;
                    default:
                        textColor = "text-other";
                        break;
                }

            }

        <h2 class="row">
            <span class="text-other m-auto">@Model.Name</span>
        </h2>
    *@
    @using (Html.BeginForm("Edit", "CharacterDetails", FormMethod.Post))
    {

        @Html.AntiForgeryToken()

        <section class="row justify-content-around">
            <div class="col-12 col-md-4 p-2">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name)
                    @Html.TextBoxFor(model => model.Name, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Name, "", htmlAttributes: new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Vision)
                    @Html.DropDownListFor(model => model.Vision, new SelectList(Enum.GetValues(typeof(Vision))), "--Select Vision--", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Vision, "", htmlAttributes: new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Weapon)
                    @Html.DropDownListFor(model => model.Weapon, new SelectList(Enum.GetValues(typeof(WeaponType))), "--Select Weapon--", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Weapon, "", htmlAttributes: new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Region)
                    @Html.DropDownListFor(model => model.Region, new SelectList(Enum.GetValues(typeof(Region))), "--Select Region--", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Region, "", htmlAttributes: new { @class = "text-danger" })

                </div>
                <div>
                    @Html.ValidationSummary(true, "", htmlAttributes: new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-12 col-md-6 d-flex justify-content-center align-items-center">
                <div class="form-group text-center pt-2 w-50">
                    <img class="img-thumbnail mb-3" src="https://via.placeholder.com/200?text=avatar+icon" alt="uploaded_avatar" />
                    <input class="form-control-file"
                           type="file"
                           name="characterIcon"
                           id="characterIcon" disabled />
                </div>
            </div>
            <div class="p-2 w-100 text-right">
                <button class="btn btn-primary btn-update"
                        type="submit"
                        name="btnUpdate"
                        id="btnUpdate">
                    Update
                </button>
            </div>
        </section>

    }
</main>

GenshinMVC/Views/CharacterDetails/Index.cshtml
@model GenshinMVC.Models.CharacterVM

@{
    ViewBag.Title = "Character Info";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Details coming soon...</h2>
</div>

GenshinMVC/Views/CharacterDetails/ViewCharacter.cshtml
@model GenshinMVC.Models.CharacterVM
@using GenshinLibrary

@{
    ViewBag.Title = Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
    var characterIconURL = "https://rerollcdn.com/GENSHIN/Characters/";
    var visionIconURL = "https://rerollcdn.com/GENSHIN/Elements/";
    var weaponIconURL = "https://rerollcdn.com/GENSHIN/Weapon/NEW/";
    string textColor;


    switch (Model.Vision)
    {
        case Vision.Anemo:
            textColor = "text-anemo";
            break;
        case Vision.Pyro:
            textColor = "text-pyro";
            break;
        case Vision.Hydro:
            textColor = "text-hydro";
            break;
        case Vision.Dendro:
            textColor = "text-dendro";
            break;
        case Vision.Cryo:
            textColor = "text-cryo";
            break;
        case Vision.Geo:
            textColor = "text-geo";
            break;
        default:
            textColor = "text-other";
            break;
    }

}

<main class="content content-col">
    <section class="row p-3">
        <div class="col-12 text-center">
            <img class="character-view-icon p-2" src="@String.Concat(characterIconURL, Model.Name, ".png")" alt="@(Model.Name)_avatar" />
            <h2 class="@textColor">@Model.Name</h2>
        </div>
        <div class="col-12">
            <div class="row w-50 m-auto">
                <div class="col-12 col-sm-6 p-2 d-flex flex-column justify-content-center align-items-center">
                    <span>@Model.Vision</span>
                    <img class="character-view-vision" src="@String.Concat(visionIconURL, "Element_", Model.Vision, ".png")" alt="@(Model.Vision)_icon" />
                </div>
                <div class="col-12 col-sm-6 p-2 d-flex flex-column justify-content-center align-items-center">
                    <span>@Model.Weapon</span>
                    <img class="character-view-weapon" src="@String.Concat(weaponIconURL, Model.Weapon, ".png")" alt="@(Model.Weapon)_icon" />
                </div>
            </div>
        </div>
    </section>
    <nav arial-label="secondary" class="navbar character-nav">
        <ul class="nav">
            <li>
                <a class="nav-link active" href="#">Skills</a>
            </li>
            <li>
                <a class="nav-link" href="#">Passive</a>
            </li>
            <li>
                <a class="nav-link" href="#">Constellations</a>
            </li>
        </ul>
        <div>
            <a class="nav-link"
               href="https://genshin-impact.fandom.com/wiki/@(Model.Name)">More info...</a>
        </div>
    </nav>
</main>

GenshinMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

GenshinMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <script src="https://kit.fontawesome.com/0bd8ca0006.js"
            crossorigin="anonymous"></script>
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/css")
</head>
<body>

    <nav aria-label="primary" class="navbar navbar-expand-md">
        <a class="brand" href="#">
            <img src="https://static.wikia.nocookie.net/gensin-impact/images/5/5a/Enemy_Cryo_Abyss_Mage_Icon.png"
                 alt="page_icon" />
        </a>
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#contentMenu"
                aria-controls="contentMenu"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span>
                <i class="fas fa-bars hamburger-icon"></i>
            </span>
        </button>

        <div class="collapse navbar-collapse" id="contentMenu">
            <ul class="navbar-nav ml-auto align-items-center">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Characters</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Weapons</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Map</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Visions</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="content-wrapper">
        <div class="container-md">
            @RenderBody()
        </div>
    </div>

    <footer class="footer footer-bg">
        <div class="container-fluid">
            <div class="row d-flex justify-content-center align-content-center">
                <span>Made with <i class="fas fa-heart"></i> by Fernandez Emmanuel</span>
            </div>
        </div>
    </footer>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("scripts", required: false)
</body>
</html>